"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CalendarClock, CheckCircle2, Clock3, Download, Gauge, RefreshCw, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import type { DashboardMetrics, Task, TaskApiResponse } from "@/types/task";

const fmt=(n:number,suffix="")=>`${Number.isFinite(n)?n:0}${suffix}`;
const entries=(o:Record<string,number>)=>Object.entries(o).sort((a,b)=>b[1]-a[1]);
function MetricCard({label,value,sub,icon}:{label:string;value:string|number;sub:string;icon:React.ReactNode}){return <article className="metric-card"><div className="metric-icon">{icon}</div><div><p>{label}</p><strong>{value}</strong><span>{sub}</span></div></article>}
function BarList({title,data,max=7}:{title:string;data:Record<string,number>;max?:number}){const list=entries(data).slice(0,max);const top=Math.max(...list.map(x=>x[1]),1);return <section className="panel"><div className="panel-head"><h3>{title}</h3><span>{list.reduce((a,b)=>a+b[1],0)} tasks</span></div><div className="bars">{list.length?list.map(([name,value])=><div className="bar-row" key={name}><div className="bar-label"><span>{name}</span><b>{value}</b></div><div className="bar-track"><i style={{width:`${Math.max(8,(value/top)*100)}%`}}/></div></div>):<p className="empty">No data available</p>}</div></section>}
function Donut({metrics}:{metrics:DashboardMetrics}){const live=metrics.live,open=metrics.open,total=Math.max(metrics.total,1);const p=Math.round(live/total*100);return <section className="panel donut-panel"><div className="panel-head"><h3>Delivery Status</h3><span>Live vs open</span></div><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(#55f6c7 0 ${p}%,#7c6cff ${p}% 100%)`}}><div><strong>{p}%</strong><span>Live</span></div></div><div className="legend"><p><i className="live-dot"/>Live <b>{live}</b></p><p><i className="open-dot"/>Open <b>{open}</b></p><p><i className="delay-dot"/>Delayed <b>{metrics.delayed}</b></p></div></div></section>}
function exportCsv(tasks:Task[]){const cols:[keyof Task,string][]=[["serial","#"],["taskType","Task Type"],["priority","Priorities"],["taskName","Task Name"],["taskDescription","Task Description"],["team","Team"],["maker","Maker"],["owner","Owner"],["checker","Checker"],["reportDate","Report Date"],["startDate","Start Date"],["eta","ETA"],["liveDate","Live Date"],["etaMissingReason","Reason if ETA missing"],["status","Status"],["comment","Comment if any"]]; const quote=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`; const csv=[cols.map(c=>quote(c[1])).join(","),...tasks.map(t=>cols.map(c=>quote(t[c[0]])).join(","))].join("\n"); const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`ls-task-manager-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
export default function Dashboard(){
 const [data,setData]=useState<TaskApiResponse|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[status,setStatus]=useState("All"),[team,setTeam]=useState("All");
 const load=useCallback(async(force=false)=>{setLoading(true);setError("");try{const r=await fetch(`/api/tasks${force?"?force=1":""}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load dashboard");setData(j);}catch(e){setError(e instanceof Error?e.message:"Unable to load dashboard");}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const id=setInterval(()=>load(),Number(process.env.NEXT_PUBLIC_REFRESH_INTERVAL_MS||30000));return()=>clearInterval(id)},[load]);
 const filtered=useMemo(()=>{if(!data)return[];const q=query.toLowerCase();return data.tasks.filter(t=>(status==="All"||t.status===status)&&(team==="All"||t.team===team)&&(!q||Object.values(t).some(v=>String(v??"").toLowerCase().includes(q))))},[data,query,status,team]);
 if(loading&&!data)return <main className="loading"><div className="loader"/><h2>Connecting to Google Sheets</h2><p>Building the live task intelligence view…</p></main>;
 if(error&&!data)return <main className="loading error-state"><AlertTriangle size={42}/><h2>Dashboard data could not load</h2><p>{error}</p><button onClick={()=>load(true)}>Try again</button></main>;
 if(!data)return null; const m=data.metrics; const statuses=["All",...Object.keys(m.byStatus)]; const teams=["All",...Object.keys(m.byTeam)];
 return <main className="dashboard-shell"><div className="aurora a1"/><div className="aurora a2"/><header className="topbar"><div><p className="eyebrow">LOKSATTA · LIVE OPERATIONS</p><h1>Task Manager <em>Command Center</em></h1><p className="subtitle">Google Sheet remains the source of truth. This dashboard is a read-only presentation layer.</p></div><div className="top-actions"><div className="sync-pill"><span/><div><b>Google Sheets Live</b><small>{data.meta.rowCount} rows · {new Date(data.meta.fetchedAt).toLocaleTimeString()}</small></div></div><button className="icon-btn" onClick={()=>load(true)} aria-label="Refresh"><RefreshCw size={18}/></button><form action="/api/auth/logout" method="post"><button className="ghost-btn">Sign out</button></form></div></header>
 <section className="metrics-grid"><MetricCard label="Total Tasks" value={m.total} sub="All tracked assignments" icon={<Activity/>}/><MetricCard label="Live Tasks" value={m.live} sub={`${fmt(m.onTimeDelivery,"%")} on-time delivery`} icon={<CheckCircle2/>}/><MetricCard label="Open Tasks" value={m.open} sub={`${m.dueThisWeek} due this week`} icon={<Clock3/>}/><MetricCard label="Delayed" value={m.delayed} sub={`${m.averageDelay} avg. delay days`} icon={<AlertTriangle/>}/><MetricCard label="ETA Coverage" value={fmt(m.etaAdherence,"%")} sub={`${m.missingEta} tasks missing ETA`} icon={<CalendarClock/>}/><MetricCard label="Turnaround" value={`${m.averageTurnaround}d`} sub="Average report-to-live" icon={<Gauge/>}/><MetricCard label="High Priority Open" value={m.highPriorityOpen} sub="Needs management attention" icon={<Sparkles/>}/><MetricCard label="Data Quality" value={fmt(m.dataQuality,"%")} sub="Required fields completed" icon={<ShieldCheck/>}/></section>
 <section className="visual-grid"><Donut metrics={m}/><section className="panel lifecycle"><div className="panel-head"><h3>Task Lifecycle</h3><span>Reported → Live</span></div>{Object.entries(m.lifecycle).map(([name,value],i)=>{const max=Math.max(m.lifecycle.reported,1);return <div className="stage" key={name}><div><span>{i+1}</span><b>{name.replace(/([A-Z])/g," $1")}</b><strong>{value}</strong></div><div className="stage-track"><i style={{width:`${Math.max(4,value/max*100)}%`}}/></div></div>})}</section><BarList title="Owner Workload" data={m.byOwner}/></section>
 <section className="visual-grid three"><BarList title="Team Distribution" data={m.byTeam}/><BarList title="Priority Mix" data={m.byPriority}/><BarList title="Task Types" data={m.byTaskType}/></section>
 <section className="visual-grid three"><BarList title="Maker Workload" data={m.byMaker}/><BarList title="Checker Workload" data={m.byChecker}/><BarList title="Delay / Missing ETA Reasons" data={m.byDelayReason}/></section>
 <section className="register panel"><div className="register-head"><div><p className="eyebrow">DETAILED OPERATIONS VIEW</p><h2>Task Register</h2><p>{filtered.length} of {data.tasks.length} tasks displayed</p></div><div className="controls"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, owner, team…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={team} onChange={e=>setTeam(e.target.value)}>{teams.map(x=><option key={x}>{x}</option>)}</select><button className="download" onClick={()=>exportCsv(filtered)}><Download size={17}/>Export CSV</button></div></div><div className="table-wrap"><table><thead><tr>{["#","Task Type","Priority","Task Name","Description","Team","Maker","Owner","Checker","Report Date","Start Date","ETA","Live Date","Reason if ETA missing","Status","Comment"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map(t=><tr key={`${t.rowNumber}-${t.serial}`} className={t.isDelayed?"risk-row":""}><td>{t.serial}</td><td>{t.taskType||"—"}</td><td><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority||"—"}</span></td><td className="task-name">{t.taskName||"—"}</td><td>{t.taskDescription||"—"}</td><td>{t.team||"—"}</td><td>{t.maker||"—"}</td><td>{t.owner||"—"}</td><td>{t.checker||"—"}</td><td>{t.reportDate||"—"}</td><td>{t.startDate||"—"}</td><td>{t.eta||"—"}</td><td>{t.liveDate||"—"}</td><td>{t.etaMissingReason||"—"}</td><td><span className={`status ${t.isLive?"live":"open"}`}>{t.status}</span></td><td>{t.comment||"—"}</td></tr>)}</tbody></table></div></section>
 <footer><span><Users size={15}/> Sheet: {data.meta.sheetTitle}</span><span>Read-only · Cache {data.meta.cacheState}</span></footer></main>
}
